spring:
  application:
    name: actuator
  boot:
    admin:
      client:
        url: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true

logging:
  level:
    com.example: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log

info:
  app:
    name: ${spring.application.name}
    description: Spring Boot Admin Demo
    version: 1.0.0